// Language definitions, visual query map, and number lookup.

export const LANGUAGES = [
  { code: "es", name: "Spanish",    native: "Español",   flag: "🇪🇸", region: "Romance",      status: "full", maxLevel: "C2" },
  { code: "zh", name: "Mandarin",   native: "普通话",     flag: "🇨🇳", region: "Sino-Tibetan", status: "full", maxLevel: "C2" },
  { code: "ja", name: "Japanese",   native: "日本語",     flag: "🇯🇵", region: "Japonic",      status: "full", maxLevel: "C2" },
  { code: "ko", name: "Korean",     native: "한국어",     flag: "🇰🇷", region: "Koreanic",     status: "full", maxLevel: "C2" },
  { code: "fr", name: "French",     native: "Français",  flag: "🇫🇷", region: "Romance",      status: "full", maxLevel: "B1" },
  { code: "de", name: "German",     native: "Deutsch",   flag: "🇩🇪", region: "Germanic",     status: "full", maxLevel: "B1" },
  { code: "it", name: "Italian",    native: "Italiano",  flag: "🇮🇹", region: "Romance",      status: "full", maxLevel: "B1" },
  { code: "pt", name: "Portuguese", native: "Português", flag: "🇧🇷", region: "Romance",      status: "full", maxLevel: "B1" },
  { code: "ru", name: "Russian",    native: "Русский",   flag: "🇷🇺", region: "Slavic",       status: "full", maxLevel: "B1" },
  { code: "el", name: "Greek",      native: "Ελληνικά",  flag: "🇬🇷", region: "Hellenic",     status: "full", maxLevel: "B1" },
  { code: "ar", name: "Arabic",     native: "العربية",   flag: "🇸🇦", region: "Semitic",      status: "soon" },
  { code: "pl", name: "Polish",     native: "Polski",    flag: "🇵🇱", region: "Slavic",       status: "soon" },
  { code: "hi", name: "Hindi",      native: "हिन्दी",    flag: "🇮🇳", region: "Indo-Aryan",   status: "soon" },
  { code: "tr", name: "Turkish",    native: "Türkçe",    flag: "🇹🇷", region: "Turkic",       status: "soon" },
  { code: "sv", name: "Swedish",    native: "Svenska",   flag: "🇸🇪", region: "Germanic",     status: "soon" },
];
;

export const VISUAL_QUERY_MAP = {
  "calendar": "Calendar",
  "kalender": "Calendar",
  "calendario": "Calendar",
  "calendrier": "Calendar",
  "bus": "Bus",
  "hotel": "Hotel",
  "server": "Waiter",
  "waiter": "Waiter",
  "waitress": "Waitress",
  "station": "Railway station",
  "bahnhof": "Railway station",
  "u-bahn": "Rapid transit",
  "airport": "Airport",
  "museum": "Museum",
  "bank": "Bank",
  "pharmacy": "Pharmacy",
  "supermarket": "Supermarket",
  "park": "Park",
  "hospital": "Hospital",
  "bridge": "Bridge",
  "ticket": "Ticket",
  "fahrkarte": "Ticket",
  "billet": "Ticket",
  "billete": "Ticket",
  "biglietto": "Ticket",
  "车票": "Ticket",
  "passport": "Passport",
  "menu": "Menu",
  "restaurant": "Restaurant",
  "coffee": "Coffee",
  "tea": "Tea",
  "bread": "Bread",
  "rice": "Rice",
  "soup": "Soup",
  "salad": "Salad",
  "apple": "Apple",
  "cheese": "Cheese",
  "shirt": "Shirt",
  "pants": "Trousers",
  "trousers": "Trousers",
  "hose": "Trousers",
  "shoes": "Shoes",
  "dress": "Dress",
  "jacket": "Jacket",
  "bag": "Bag",
  "gift": "Gift",
  "souvenir": "Souvenir",
  "postcard": "Postcard",
  "flowers": "Flowers",
  "book": "Book",
  "perfume": "Perfume",
  "toy": "Toy",
  "mother": "Mother",
  "father": "Father",
  "brother": "Brother",
  "sister": "Sister",
  "tram": "Tram",
  "subway": "Rapid transit",
  "taxi": "Taxi",
  "bicycle": "Bicycle",
  "car": "Car",
  "airplane": "Airplane",
  "train": "Train",
  "zug": "Train",
  "map": "Map",
  "umbrella": "Umbrella",
  "clock": "Clock",
  "breakfast": "Breakfast",
  "dinner": "Dinner",
  "phone": "Mobile phone",
  "water": "Water",
  "fahrplan": "Timetable"
};
;

export const NUMBER_VALUE_MAP = {
  "0": 0, "zero": 0, "null": 0, "cero": 0, "zéro": 0, "零": 0,
  "1": 1, "one": 1, "eins": 1, "uno": 1, "un": 1, "une": 1, "一": 1,
  "2": 2, "two": 2, "zwei": 2, "dos": 2, "deux": 2, "due": 2, "二": 2,
  "3": 3, "three": 3, "drei": 3, "tres": 3, "trois": 3, "tre": 3, "三": 3,
  "4": 4, "four": 4, "vier": 4, "cuatro": 4, "quatre": 4, "quattro": 4, "四": 4,
  "5": 5, "five": 5, "fünf": 5, "cinco": 5, "cinq": 5, "cinque": 5, "五": 5,
  "6": 6, "six": 6, "sechs": 6, "seis": 6, "sei": 6, "六": 6,
  "7": 7, "seven": 7, "sieben": 7, "siete": 7, "sept": 7, "sette": 7, "七": 7,
  "8": 8, "eight": 8, "acht": 8, "ocho": 8, "huit": 8, "otto": 8, "八": 8,
  "9": 9, "nine": 9, "neun": 9, "nueve": 9, "neuf": 9, "nove": 9, "九": 9,
  "10": 10, "ten": 10, "zehn": 10, "diez": 10, "dix": 10, "dieci": 10, "十": 10
};

;
